functionsDirectory = "/root/.openclaw/workspace/sap-pmm-internal/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/root/.openclaw/workspace/sap-pmm-internal/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'Static site ready'"
functions = "/root/.openclaw/workspace/sap-pmm-internal/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions.lab-ai]
timeout = 60.0

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/subscribe"
to = "/subscribe.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/newsletter-preview"
to = "/newsletter-preview.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]